version: "3"
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db_tenant"
    volumes:
      - ./docker_data/db:/var/lib/postgresql/data:rw
