# Generated by Django 3.2.7 on 2021-10-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('dcreate', models.DateTimeField(auto_now_add=True)),
                ('dupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
